// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVbitkfRzphxJ1kG7pnPy_N0uxrA3LQc',
    appId: '1:388828720336:web:4183fc4755a6ccefcf82d5',
    messagingSenderId: '388828720336',
    projectId: 'boardinghouse-90aeb',
    authDomain: 'boardinghouse-90aeb.firebaseapp.com',
    storageBucket: 'boardinghouse-90aeb.firebasestorage.app',
    measurementId: 'G-E3Y6080Z2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6t3LkKYgeosG6lZjEfHWW55jLX0Xyag',
    appId: '1:388828720336:android:643990c38d01fcfacf82d5',
    messagingSenderId: '388828720336',
    projectId: 'boardinghouse-90aeb',
    storageBucket: 'boardinghouse-90aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-hnVPqhss8E3w_bhE4QEHLMee21JAhU',
    appId: '1:388828720336:ios:85170bd3c99a69b5cf82d5',
    messagingSenderId: '388828720336',
    projectId: 'boardinghouse-90aeb',
    storageBucket: 'boardinghouse-90aeb.firebasestorage.app',
    iosClientId: '388828720336-miikemb6ingn66fb7t5cmi2j3u9pto8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalboarding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-hnVPqhss8E3w_bhE4QEHLMee21JAhU',
    appId: '1:388828720336:ios:85170bd3c99a69b5cf82d5',
    messagingSenderId: '388828720336',
    projectId: 'boardinghouse-90aeb',
    storageBucket: 'boardinghouse-90aeb.firebasestorage.app',
    iosClientId: '388828720336-miikemb6ingn66fb7t5cmi2j3u9pto8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalboarding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUVbitkfRzphxJ1kG7pnPy_N0uxrA3LQc',
    appId: '1:388828720336:web:3c3347b5f81e90accf82d5',
    messagingSenderId: '388828720336',
    projectId: 'boardinghouse-90aeb',
    authDomain: 'boardinghouse-90aeb.firebaseapp.com',
    storageBucket: 'boardinghouse-90aeb.firebasestorage.app',
    measurementId: 'G-8JJEBD2GCZ',
  );

}