import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart'; // ← Added Firebase Core

// ── Firebase Options ────────────────────────────────────────
import 'firebase_options.dart'; // ← Generated by FlutterFire CLI

// ── Feature ViewModels & Repositories ───────────────────────
import 'features/auth/data/repositories/auth_repository.dart'; // ← Added Auth Repo
import 'features/auth/viewmodels/auth_viewmodel.dart';         // ← Added Auth ViewModel
import 'features/bookings/viewmodels/booking_viewmodel.dart';
import 'features/properties/viewmodels/home_viewmodel.dart';
import 'features/saved/viewmodels/saved_viewmodel.dart';
import 'features/account/viewmodels/account_viewmodel.dart';
import 'features/map/viewmodels/map_viewmodel.dart';

// ── App Shell ───────────────────────────────────────────────
import 'app.dart';

void main() async { 
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the generated options for your current platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Lock to portrait mode
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Make status bar transparent (edge-to-edge look)
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );

  runApp(
    MultiProvider(
      providers: [
        // ── Authentication Providers ──
        Provider<AuthRepository>(create: (_) => AuthRepository()),
        ChangeNotifierProvider<AuthViewModel>(
          create: (context) => AuthViewModel(), // <--- Tininggal na natin ang parameter dito!
        ),

        // ── Existing Feature Providers ──
        Provider(create: (_) => HomeViewModel()),
        Provider(create: (_) => BookingViewModel()),
        ChangeNotifierProvider(create: (_) => SavedViewModel()),
        ChangeNotifierProvider(create: (_) => AccountViewModel()),
        Provider(create: (_) => MapViewModel()),
      ],
      child: const App(),
    ),
  );
}